### ISSUE TITLE
Themeforest approving this instead of TGMPA

### ISSUE THREAD

**Issue by dingo-d** [bitfade/pixelentity-theme-bundled-plugins#1]
Hi!

I saw your thread about plugin activation on tf forums, and was wondering did you include it in your themes instead of TGM PA? It's much shorter and easier to use (understand) than TGM PA. 

If so, are your themes approved?

**Comment by Zackio** [comment]
A reviewer said that other plugin installers are allowed but could delay review as they would have to do further checking. You would probably find this isn't consistently applied however... plus things randomly change.

**Comment by dingo-d** [comment]
But in the end they are not forbidden, which is important, no? :)

**Comment by Zackio** [comment]
Sure. I would just point them to the requirements page in the notes :)

See where is says `or simular solution`
https://help.market.envato.com/hc/en-us/articles/202822450-WordPress-Theme-Submission-Requirements

**Comment by bitfade** [comment]
Hi,
our latest theme uses it and we had no issues with the review.

**Comment by dingo-d** [comment]
Hi! Thanks for the answer :)

While you're here, can I ask you if you've managed to implement a way to pull required plugins that you get from a wordpress repo, like CF7? I've found a way to pull the plugin from the repo, but I am struggling to install it, all I get is that I download a zip file on install click.

**Comment by bitfade** [comment]
The issue for us was dealing with plugins not hosted on wp.org to begin with so i didn't do any research on that matter.

**Comment by dingo-d** [comment]
Oh, ok, thanks for the answer :)
